import { useMemo } from 'react'
import { useMovable } from '../lib/movable'
import { setAppState, useAppSlice } from '../state/store'
import type { TimelineEvent } from '../types'

const REPORT_KINDS = new Set([
  'scenario.loaded',
  'alarm',
  'agency.activated',
  'mci.declared',
  'mci.closed',
  'casualty.count',
  'command.unified',
  'command.terminated',
  'interagency.request',
  'interagency.closed',
  'alert.mayday',
  'par.start',
  'par.complete',
  'exposures.set',
])

function line(ev: TimelineEvent): string {
  const p = (ev.payload ?? {}) as Record<string, unknown>
  switch (ev.kind) {
    case 'alarm':
      return `Alarm level: ${String(p.level ?? '').toUpperCase()}`
    case 'agency.activated':
      return `${String(p.agency)} activated — ${String(p.note ?? '')}`
    case 'mci.declared':
      return `MCI declared at ${String(p.location ?? '')} (initial count ${String(p.initialCount ?? '?')})`
    case 'mci.closed':
      return `MCI closed — final patient count ${String(p.final ?? '?')}`
    case 'casualty.count':
      return `Casualty count: ${String(p.red)} red / ${String(p.yellow)} yellow / ${String(p.green)} green · ${String(p.transported)} transported`
    case 'command.unified':
      return `Unified Command established: ${(Array.isArray(p.agencies) ? (p.agencies as string[]) : []).join(', ')}`
    case 'command.terminated':
      return `Command terminated at ${String(p.duration ?? '')} by ${String(p.by ?? '')}`
    case 'interagency.request':
      return `Interagency request ${String(p.id)}: ${String(p.from)} → ${String(p.to)} — ${String(p.text)}`
    case 'interagency.closed':
      return `Request ${String(p.id)} closed — ${String(p.resolution ?? '')}`
    case 'alert.mayday':
      return `MAYDAY — ${String(p.callsign ?? '')}: ${String(p.text ?? '')}`
    case 'par.start':
      return `Emergency roll call initiated`
    case 'par.complete':
      return `PAR complete — ${String(p.result ?? '')}`
    case 'exposures.set':
      return `Exposure designations set (${String(p.count)})`
    case 'scenario.loaded':
      return `Scenario loaded: ${String(p.name ?? '')}`
    default:
      return ev.kind
  }
}

/**
 * After-action report (Prompt 8B closing beat): the incident you just watched,
 * already a document. Compiled from the same event log that drove the map;
 * PRINT hands it to the browser's print dialog for PDF export.
 */
export function AarPanel() {
  const mvAar = useMovable('aar')
  const { aarOpen, timeline, incident, units, scenario } = useAppSlice((s) => ({ aarOpen: s.aarOpen, timeline: s.timeline, incident: s.incident, units: s.units, scenario: s.scenario }))

  const rows = useMemo(() => timeline.filter((ev) => REPORT_KINDS.has(ev.kind)), [timeline])
  const byAgency = useMemo(() => {
    const m = new Map<string, number>()
    for (const u of Object.values(units)) m.set(u.agency, (m.get(u.agency) ?? 0) + 1)
    return [...m.entries()].sort((a, b) => b[1] - a[1])
  }, [units])

  if (!aarOpen) return null

  return (
    <div className="aar-backdrop">
      <div {...mvAar} className="aar-panel glass" id="aar-report">
        <div className="panel-head">
          <span className="card-title">AFTER-ACTION SUMMARY {scenario?.drill ? '· DRILL — SIMULATED INCIDENT' : ''}</span>
          <button className="chip chip-btn" onClick={() => window.print()}>
            ⎙ PRINT / PDF
          </button>
          <button className="panel-close" onClick={() => setAppState({ aarOpen: false })}>
            ✕
          </button>
        </div>
        <div className="aar-body">
          <h2>{incident?.address ?? 'Incident'}</h2>
          <div className="aar-meta">
            <span>INCIDENT {incident?.id}</span>
            <span>FINAL ALARM {incident?.alarmLevel?.toUpperCase() ?? '—'}</span>
            <span>UNITS ON THE PICTURE {Object.keys(units).length}</span>
          </div>
          <div className="aar-agencies">
            {byAgency.map(([a, n]) => (
              <span key={a} className="chip">
                {a} · {n}
              </span>
            ))}
          </div>
          <div className="intel-section-title">Key Events</div>
          {rows.map((ev, i) => (
            <div key={`${ev.t}-${i}`} className="aar-row">
              <span className="aar-time">{new Date(ev.t).toLocaleTimeString()}</span>
              <span className="aar-line">{line(ev)}</span>
            </div>
          ))}
          <div className="aar-foot">
            Generated by KEYSTONE from the live event log — every entry above was rendered on the common operating
            picture as it happened.
          </div>
        </div>
      </div>
    </div>
  )
}
